version: "3.7"

services:
    external-service:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
        - "3000:3000"
        env_file:
        - .env/common.env
        volumes:
        - ./src:/app/src
        - ./node_modules:/app/node_modules